Replace tabs with spaces in docker-wipe.

diff --git a/home/bin/docker-wipe b/home/bin/docker-wipe
--- a/home/bin/docker-wipe
+++ b/home/bin/docker-wipe
@@ -73,7 +73,7 @@ function removeAll {
 echo '## Docker-wipe script ###'
 
 case "$1" in
-	containers)
+  containers)
     if [[ $CONFIRM == 'y' ]]; then
       removeContainers
     else
@@ -84,8 +84,8 @@ case "$1" in
         removeContainers
       fi
     fi
-	  ;;
-	images)
+    ;;
+  images)
     if [[ $CONFIRM == 'y' ]]; then
       removeImages
     else
@@ -96,8 +96,8 @@ case "$1" in
         removeImages
       fi
     fi
-	  ;;
-	volumes)
+    ;;
+  volumes)
     if [[ $CONFIRM == 'y' ]]; then
       removeVolumes
     else
@@ -108,7 +108,7 @@ case "$1" in
         removeVolumes
       fi
     fi
-	  ;;
+    ;;
   all)
     if [[ $CONFIRM == 'y' ]]; then
       removeAll
@@ -121,10 +121,10 @@ case "$1" in
       fi
     fi
     ;;
-	*)
-		echo 'Wrong or missing parameter.'
+  *)
+    echo 'Wrong or missing parameter.'
     echo ''
-	  echo $"Usage: $0 {containers|images|volumes|all} {parameter}"
+    echo $"Usage: $0 {containers|images|volumes|all} {parameter}"
     echo 'Commands:'
     echo '  containers   - delete all containers'
     echo '  images       - delete all images'
@@ -138,7 +138,7 @@ case "$1" in
     echo $"$0 containers    - delete all containers"
     echo $"$0 containers y  - delete all containers without confirmation"
     echo ''
-	  exit 1
+    exit 1
 esac
 
 echo ''
